### ISSUE TITLE
GHC HEAD trouble

### ISSUE THREAD

**Issue by ggreif** [clash-lang/ghc-tcplugins-extra#1]
```
Preprocessing library ghc-tcplugins-extra-0.1...
[1 of 1] Compiling GHC.TcPluginM.Extra ( src/GHC/TcPluginM/Extra.hs, dist/dist-sandbox-fa345477/build/GHC/TcPluginM/Extra.o )

src/GHC/TcPluginM/Extra.hs:48:20: error:
    Module 'HscTypes' does not export 'FoundHs(..)'
Failed to install ghc-tcplugins-extra-0.1
```

I think `FoundHs` is now named `FindResult`.

**Comment by christiaanb** [comment]
Thanks for the report. That part of GHC has been a moving target, where a patch has been applied, then reverted, then applied again, and now apparently reverted again...

**Comment by ggreif** [comment]
@christiaanb okay, I see. That sucks :-( I'll try to patch it up for myself, so that I can demo CLaSH for our FPGA guys sometime in the next few weeks. Or I simply use the other computer with the platform on it. Thanks anyway!

**Comment by christiaanb** [comment]
Ah... but this package won't be your biggest problem then...

The CLaSH binary is a slight modification of the GHC(i) binary. Currently it's based on the 7.10 branch binary, I don't know if it'll build against the HEAD GHC API.

**Comment by ggreif** [comment]
Well, I think the API won't cause the pain. I am building in a cabal sandbox and it seems to have trouble invoking the typ checker plugin (which builds now just fine), as it cannot prove certain type equalities. More details in the next few days. Btw., have you ever built CLaSH in a sandbox?

**Comment by christiaanb** [comment]
I develop CLaSH in a sandbox. I have once installed CLaSH from hackage into a sandbox, so it's not something I do often. Also, when installed in a sandbox, you cannot run CLaSH as you normally would: https://github.com/clash-lang/clash-compiler/wiki/FAQ#how-do-i-run-clash-within-a-cabal-sandbox

**Comment by christiaanb** [comment]
Just released a version that compiles against ghc8-rc1 on hackage: http://hackage.haskell.org/package/ghc-tcplugins-extra-0.2
