### ISSUE TITLE
9.3 HEAD: Module ‘GHC.Tc.Types’ does not export ‘TcPluginResult(..)’

### ISSUE THREAD

**Issue by Mikolaj** [clash-lang/ghc-tcplugins-extra#21]
I hope this is some trivial API change and it would be easy to make ghc-tcplugins-extra work with head? I need this to be able to repro a suspect GHC bug with HEAD, but this will probably also make ghc-tcplugins-extra ready for GHC 9.4.1.

```
Failed to build ghc-tcplugins-extra-0.4.2.
Build log (
/home/mikolaj/.cabal/logs/ghc-9.3.20220316/ghc-tcplugins-extra-0.4.2-03780bc76cabaa0f8a3b8fb908cbadb752b4bbb38f36e6794751c3d459ceb2d9.log
):
Configuring library for ghc-tcplugins-extra-0.4.2..
Preprocessing library for ghc-tcplugins-extra-0.4.2..
Building library for ghc-tcplugins-extra-0.4.2..
[1 of 1] Compiling GHC.TcPluginM.Extra ( src/GHC/TcPluginM/Extra.hs, dist/build/GHC/TcPluginM/Extra.o, dist/build/GHC/TcPluginM/Extra.dyn_o )

src/GHC/TcPluginM/Extra.hs:64:37: error:
    Module ‘GHC.Tc.Types’ does not export ‘TcPluginResult(..)’
   |
64 | import GHC.Tc.Types (TcPlugin (..), TcPluginResult (..))
   |                                     ^^^^^^^^^^^^^^^^^^^
```

Looking at `compiler/GHC/Tc/Types.hs`

```Haskell
        -- Constraint solver plugins
        TcPlugin(..),
        TcPluginSolveResult(TcPluginContradiction, TcPluginOk, ..),
        TcPluginRewriteResult(..),
        TcPluginSolver, TcPluginRewriter,
        TcPluginM(runTcPluginM), unsafeTcPluginTcM,
```

perhaps the API just got more precise?

**Comment by Mikolaj** [comment]
I can't see anything about that in https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.4. @mpickering should I file this somewhere?

**Comment by Mikolaj** [comment]
BTW, I see the guide still mentions the old type (and no other mentions in GHC source):

```
~/r/ghc$ git grep TcPluginResult
docs/users_guide/extending_ghc.rst:    type TcPluginSolver = [Ct] -> [Ct] -> [Ct] -> TcPluginM TcPluginResult
docs/users_guide/extending_ghc.rst:   should return a ``TcPluginResult`` that indicates whether a
docs/users_guide/extending_ghc.rst:    solve :: [Ct] -> [Ct] -> [Ct] -> TcPluginM TcPluginResult
```

**Comment by Mikolaj** [comment]
May I help somehow with this fix?

**Comment by sheaf** [comment]
The `TcPluginResult` type was changed to be a record instead of a sum, and renamed to `TcPluginSolveResult` to distinguish from `TcPluginRewriteResult` for type-family rewriting. `TcPluginContradiction` and `TcPluginOk` pattern synonyms have been bundled with `TcPluginSolveResult` to recover the old "sum type" functionality.

In this instance you should be able to rename `TcPluginResult` to `TcPluginSolveResult`. I will update the documentation/migration guide.

**Comment by Mikolaj** [comment]
Migration guide entry: https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.4#changes-to-typechecker-plugins

**Comment by Mikolaj** [comment]
Dear maintainers: ping! :) [GHC 9.4.1-alpha1 is now available](https://discourse.haskell.org/t/ghc-9-4-1-alpha1-is-now-available/4455).

**Comment by christiaanb** [comment]
Sorry, we're aware of the issue, but we haven't found the time yet to make a patch.

**Comment by Mikolaj** [comment]
Oh, good, thank you. We are waiting patiently. :)

**Comment by Mikolaj** [comment]
Thank you so much!

**Comment by christiaanb** [comment]
Now released on hackage: https://hackage.haskell.org/package/ghc-tcplugins-extra-0.4.3

**Comment by Mikolaj** [comment]
Amazing! Woo-hoo!
